    PREFIX owl: <http://www.w3.org/2002/07/owl#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    SELECT ?s (MAX(?slang1) AS ?lang1) (MAX(?slang2) AS ?lang2)
    WHERE {
      {?s a owl:Class} UNION {?s a owl:ObjectProperty} UNION {?s a owl:DatatypeProperty} UNION {?s a owl:AnnotationProperty}
      OPTIONAL {?s rdfs:label ?label . BIND(lang(?label) AS ?lang)
        BIND(IF(?lang="en", ?label, "") AS ?slang1)
        BIND(IF(?lang="de", ?label, "") AS ?slang2)
      }
      }
    GROUP BY ?s
    ORDER BY ?s
